# Generated by Django 4.0.3 on 2022-03-22 20:11

import django.core.management.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=8)),
                ('senha', models.CharField(blank=True, default=django.core.management.utils.get_random_secret_key, max_length=50)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
