# Generated by Django 4.0.3 on 2022-03-22 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usuarios_id_alter_usuarios_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='login',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(blank=True, default='F2ZlF1IiGm', max_length=15),
        ),
    ]
